version: '3.2'

#TODO change build to image: IMAGE LINK:latest
services:

  mn1:
    build: ./docker
    restart: unless-stopped
    environment:
      masternodeprivkey: "PUT YOUR KEY HERE"
    ports:    
      - "25001:5333"
    
  mn2:
    build: ./docker
    restart: unless-stopped
    environment:
      coin: "happyleaf"
      ip: "0.0.0.0"
      masternodeprivkey: "PUT YOUR KEY HERE"
    ports:    
      - "25002:5333"
      
      
      
    
